export const CAROUSEL_PRESETS = [
  {
    slug: "coffeecorner",
    description: "Your neighborhood coffee shop ☕🍩",
    image: "preset-1.png",
    icons: [
      { id: 1, logo: "simple-icons:instagram" },
      { id: 2, logo: "simple-icons:facebook" },
      { id: 3, logo: "simple-icons:gmail" },
    ],
    links: [
      { id: 1, title: "Online Menu & Ordering" },
      { id: 2, title: "Find Us!" },
      { id: 3, title: "Contact" },
      { id: 4, title: "Our Story" },
    ],
    preferences: {
      backgroundType: "FLAT",
      backgroundColor: "#2c1f14",
      profilePictureRadius: "0.5rem",
      profilePictureBorderColor: "#997a61",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#997a61",
      slugTextWeight: "600",
      slugTextSize: "1.5rem",
      slugFontFamily: "'Lora'",
      headerTextColor: "#aa998b",
      headerTextWeight: "400",
      headerTextSize: "1rem",
      headerFontFamily: "'Noto Sans'",
      linkBackgroundColor: "#6b4b3e",
      linkTextColor: "#f5f5f5",
      linkTextWeight: "400",
      linkTextSize: "0.8rem",
      linkFontFamily: "'Noto Sans'",
      isLinkShadow: false,
      linkHoverBackgroundColor: "#7b4a2e",
      linkBorderRadius: "0.5rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#7b4a2e",
      isIconShadow: false,
      iconLogoColor: "#f5f5f5",
      iconHoverBackgroundColor: "#a66240",
    },
  },
  {
    slug: "explore-with-anna",
    description: "Travel Blogger & Adventurer ✈️",
    image: "preset-2.png",
    icons: [
      { id: 1, logo: "simple-icons:instagram" },
      { id: 2, logo: "simple-icons:pinterest" },
      { id: 3, logo: "simple-icons:youtube" },
    ],
    links: [
      { id: 1, title: "Latest Travel Blog" },
      { id: 2, title: "Travel Vlogs! 🧭📍" },
      { id: 3, title: "Tips & Gear" },
    ],
    preferences: {
      backgroundType: "GRADIENT",
      backgroundGradientStart: "#b2c6b6",
      backgroundGradientEnd: "#f5f5f5",
      profilePictureRadius: "5rem",
      profilePictureBorderColor: "#2c3e50",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#2c3e50",
      slugTextWeight: "700",
      slugTextSize: "1.25rem",
      slugFontFamily: "'Roboto'",
      headerTextColor: "#272525",
      headerTextWeight: "400",
      headerTextSize: "1rem",
      headerFontFamily: "'Noto Sans'",
      linkBackgroundColor: "#babdbe",
      linkTextColor: "#2c3e50",
      linkTextWeight: "600",
      linkTextSize: "0.8rem",
      linkFontFamily: "'Noto Sans'",
      isLinkShadow: true,
      linkShadowColor: "#e7e5e5",
      linkShadowWeight: "medium",
      linkHoverBackgroundColor: "#bdc3c7",
      linkBorderRadius: "5rem",
      linkPadding: "0.5rem",
      iconBackgroundColor: "#e8ecd6",
      isIconShadow: true,
      iconShadowColor: "#e7e5e5",
      iconShadowWeight: "light",
      iconLogoColor: "#b75a48",
      iconHoverBackgroundColor: "#d1d9c6",
    },
  },
  {
    slug: "blitz_corp",
    description:
      "Experience high-tech innovation with Blitz Corp, where the future is now.",
    image: "preset-3.png",
    icons: [
      { id: 1, logo: "simple-icons:linkedin" },
      { id: 2, logo: "simple-icons:x" },
      { id: 3, logo: "simple-icons:youtube" },
      { id: 4, logo: "simple-icons:github" },
    ],
    links: [
      { id: 1, title: "Innovative Solutions" },
      { id: 2, title: "Our Story" },
      { id: 3, title: "Contact Us" },
    ],
    preferences: {
      backgroundType: "FLAT",
      backgroundColor: "#272525",
      profilePictureRadius: "1rem",
      profilePictureBorderColor: "#3e7a70",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#f5f3f3",
      slugTextWeight: "800",
      slugTextSize: "1.5rem",
      slugFontFamily: "'Audiowide'",
      headerTextColor: "#f5f3f3",
      headerTextWeight: "400",
      headerTextSize: "1rem",
      headerFontFamily: "'Roboto'",
      linkBackgroundColor: "#f7f1e3",
      linkTextColor: "#272525",
      linkTextWeight: "700",
      linkTextSize: "0.8rem",
      linkFontFamily: "'Roboto'",
      isLinkShadow: true,
      linkShadowColor: "#3e7a70",
      linkShadowWeight: "medium",
      linkHoverBackgroundColor: "#d1ccc0",
      linkBorderRadius: "0.5rem",
      linkPadding: "0.5rem",
      iconBackgroundColor: "#f5f3f3",
      isIconShadow: false,
      iconLogoColor: "#3e7a70",
      iconHoverBackgroundColor: "#dcdcdc",
    },
  },
  {
    slug: "threadhaus",
    description: "Elevated essentials. Modern uniform.",
    image: "preset-4.png",
    icons: [
      { id: 1, logo: "simple-icons:shopify" },
      { id: 2, logo: "simple-icons:instagram" },
      { id: 3, logo: "simple-icons:tiktok" },
    ],
    links: [
      { id: 1, title: "Shop New Arrivals" },
      { id: 2, title: "Style Lookbook" },
      { id: 3, title: "Join Our Drop List" },
    ],
    preferences: {
      backgroundType: "FLAT",
      backgroundColor: "#f6f3e7",
      profilePictureRadius: "0.25rem",
      profilePictureBorderColor: "#2c3e50",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#1a1a1a",
      slugTextWeight: "800",
      slugTextSize: "1.5rem",
      slugFontFamily: "'Ribeye'",
      headerTextColor: "#333333",
      headerTextWeight: "400",
      headerTextSize: "1rem",
      headerFontFamily: "'Noto Sans'",
      linkBackgroundColor: "#1a1a1a",
      linkTextColor: "#ffffff",
      linkTextWeight: "600",
      linkTextSize: "0.8rem",
      linkFontFamily: "'Noto Sans'",
      isLinkShadow: false,
      linkHoverBackgroundColor: "#333333",
      linkBorderRadius: "0.25rem",
      linkPadding: "0.85rem",
      iconBackgroundColor: "#1a1a1a",
      isIconShadow: false,
      iconLogoColor: "#ffffff",
      iconHoverBackgroundColor: "#333333",
    },
  },
  {
    slug: "matheus-mortari",
    description: "I'm a full-stack dev :)",
    image: "preset-5.png",
    icons: [
      { id: 1, logo: "simple-icons:github" },
      { id: 2, logo: "simple-icons:linkedin" },
      { id: 3, logo: "simple-icons:gmail" },
    ],
    links: [
      { id: 1, title: "Coding Playlist! 🎵" },
      { id: 2, title: "My Blog" },
      { id: 3, title: "Contact Me 🤙" },
      { id: 4, title: "Check out my new project!" },
    ],
    preferences: {
      backgroundType: "GRADIENT",
      backgroundGradientStart: "#08080e",
      backgroundGradientEnd: "#19192e",
      profilePictureRadius: "5rem",
      profilePictureBorderColor: "#605492",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#ececec",
      slugTextWeight: "700",
      slugTextSize: "1.75rem",
      slugFontFamily: "'Montserrat'",
      headerTextColor: "#ececec",
      headerTextWeight: "600",
      headerTextSize: "1rem",
      headerFontFamily: "'Noto Sans'",
      linkBackgroundColor: "#605492",
      linkTextColor: "#ececec",
      linkTextWeight: "700",
      linkTextSize: "0.8rem",
      linkFontFamily: "'Noto Sans'",
      isLinkShadow: false,
      linkHoverBackgroundColor: "#4c4083",
      linkBorderRadius: "5rem",
      linkPadding: "0.5rem",
      iconBackgroundColor: "#42413e",
      isIconShadow: true,
      iconShadowColor: "#42413e",
      iconShadowWeight: "light",
      iconLogoColor: "#ececec",
      iconHoverBackgroundColor: "#4c4083",
    },
  },
  {
    slug: "devopsdojo",
    description: "CI/CD, IaC & container chaos. 🛠️🐳",
    image: "preset-6.png",
    icons: [
      { id: 1, logo: "simple-icons:github" },
      { id: 2, logo: "simple-icons:bluesky" },
      { id: 3, logo: "simple-icons:linkedin" },
      { id: 4, logo: "simple-icons:spotify" },
    ],
    links: [
      { id: 1, title: "Infra Templates (IaC)" },
      { id: 2, title: "DevOps Blog" },
    ],
    preferences: {
      backgroundType: "FLAT",
      backgroundColor: "#0f0f0f",
      profilePictureRadius: "0.25rem",
      profilePictureBorderColor: "#2c3e50",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#5ec2c1",
      slugTextWeight: "700",
      slugTextSize: "1.5rem",
      slugFontFamily: "'Ubuntu Mono'",
      headerTextColor: "#e0e0e0",
      headerTextWeight: "400",
      headerTextSize: "1rem",
      headerFontFamily: "'Roboto'",
      linkBackgroundColor: "#1e2a38",
      linkTextColor: "#f5f5f5",
      linkTextWeight: "600",
      linkTextSize: "0.8rem",
      linkFontFamily: "'Ubuntu Mono'",
      isLinkShadow: true,
      linkShadowColor: "#0e7490",
      linkShadowWeight: "medium",
      linkHoverBackgroundColor: "#273849",
      linkBorderRadius: "0.5rem",
      linkPadding: "0.85rem",
      iconBackgroundColor: "#1e2a38",
      isIconShadow: true,
      iconShadowColor: "#0e7490",
      iconShadowWeight: "light",
      iconLogoColor: "#5ec2c1",
      iconHoverBackgroundColor: "#314658",
    },
  },
  {
    slug: "lofi-lounge",
    description: "Chill beats for studying & relaxing 🎵",
    image: "preset-7.png",
    icons: [
      { id: 1, logo: "simple-icons:spotify" },
      { id: 2, logo: "simple-icons:soundcloud" },
      { id: 3, logo: "simple-icons:youtube" },
    ],
    links: [
      { id: 1, title: "Listen on Spotify" },
      { id: 2, title: "Lofi Playlists" },
      { id: 3, title: "Merch & Vinyls" },
    ],
    preferences: {
      backgroundType: "GRADIENT",
      backgroundGradientStart: "#1e3c72",
      backgroundGradientEnd: "#2a5298",
      profilePictureRadius: "5rem",
      profilePictureBorderColor: "#2a5298",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#ffffff",
      slugTextWeight: "700",
      slugTextSize: "1.5rem",
      slugFontFamily: "'Lora'",
      headerTextColor: "#ffffff",
      headerTextWeight: "400",
      headerTextSize: "1rem",
      headerFontFamily: "'Noto Sans'",
      linkBackgroundColor: "#ffafcc",
      linkTextColor: "#2a5298",
      linkTextWeight: "800",
      linkTextSize: "0.8rem",
      linkFontFamily: "'Ubuntu Mono'",
      isLinkShadow: true,
      linkShadowColor: "#e78ea9",
      linkShadowWeight: "medium",
      linkHoverBackgroundColor: "#e78ea9",
      linkBorderRadius: "1rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#ffafcc",
      isIconShadow: true,
      iconShadowColor: "#e78ea9",
      iconShadowWeight: "medium",
      iconLogoColor: "#2a5298",
      iconHoverBackgroundColor: "#e78ea9",
    },
  },
  {
    slug: "studio-sakura",
    description: "Traditional Irezumi & Neo-Japanese Ink 🗾",
    image: "preset-8.png",
    icons: [
      { id: 1, logo: "simple-icons:instagram" },
      { id: 3, logo: "simple-icons:tiktok" },
    ],
    links: [
      { id: 1, title: "Book a Session" },
      { id: 2, title: "Tattoo Gallery 🎨" },
      { id: 3, title: "Find Our Studio 🏢" },
    ],
    preferences: {
      backgroundType: "GRADIENT",
      backgroundGradientStart: "#1f0e14",
      backgroundGradientEnd: "#3e1c24",
      profilePictureRadius: "0.5rem",
      profilePictureBorderColor: "#2c3e50",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#fdd9d2",
      slugTextWeight: "700",
      slugTextSize: "1.5rem",
      slugFontFamily: "'Amarante'",
      headerTextColor: "#f5f5f5",
      headerTextWeight: "400",
      headerTextSize: "1rem",
      headerFontFamily: "'Lora'",
      linkBackgroundColor: "#7a304d",
      linkTextColor: "#f5f5f5",
      linkTextWeight: "600",
      linkTextSize: "1rem",
      linkFontFamily: "'Roboto'",
      isLinkShadow: false,
      linkHoverBackgroundColor: "#a3425d",
      linkBorderRadius: "0.75rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#a3425d",
      isIconShadow: false,
      iconLogoColor: "#fff0f0",
      iconHoverBackgroundColor: "#c85c70",
    },
  },
]
