export const THEMES: { title: string, preferences: UserPreferences }[] = [
  {
    title: "Mint",
    preferences: {
      backgroundType: "FLAT",
      backgroundColor: "#4a5d51",
      profilePictureRadius: "5rem",
      profilePictureBorderColor: "#3f5243",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#212b29",
      slugTextWeight: "800",
      slugTextSize: "1.25rem",
      slugFontFamily: "'Playfair Display', serif",
      headerTextColor: "#a3b4b0",
      headerTextWeight: "400",
      headerTextSize: "1.1rem",
      headerFontFamily: "'Roboto', sans-serif",
      linkBackgroundColor: "#5e7464",
      linkTextColor: "#171c1b",
      linkTextWeight: "600",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#3f5243",
      linkShadowWeight: "medium",
      linkHoverBackgroundColor: "#3f5243",
      linkBorderRadius: "5rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#3f5243",
      isIconShadow: true,
      iconShadowColor: "#3f5243",
      iconShadowWeight: "medium",
      iconLogoColor: "#ebe8e8",
      iconHoverBackgroundColor: "#5e7464",
    },
  },
  {
    title: "Arctic White",
    preferences: {
      backgroundType: "FLAT",
      backgroundColor: "#e6ecf0",
      profilePictureRadius: "1rem",
      profilePictureBorderColor: "#404345",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#2c3e50",
      slugTextWeight: "800",
      slugTextSize: "1.1rem",
      slugFontFamily: "'Roboto', sans-serif",
      headerTextColor: "#2c3e50",
      headerTextWeight: "400",
      headerTextSize: "1rem",
      headerFontFamily: "'Roboto', sans-serif",
      linkBackgroundColor: "#ecf0f1",
      linkTextColor: "#2c3e50",
      linkTextWeight: "400",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#404345",
      linkShadowWeight: "light",
      linkHoverBackgroundColor: "#bdc3c7",
      linkBorderRadius: "1rem",
      linkPadding: "0.5rem",
      iconBackgroundColor: "#bdc3c7",
      isIconShadow: true,
      iconShadowColor: "#404345",
      iconShadowWeight: "medium",
      iconLogoColor: "#2c3e50",
      iconHoverBackgroundColor: "#ecf0f1",
    },
  },
  {
    title: "Arctic Blue",
    preferences: {
      backgroundType: "GRADIENT",
      backgroundGradientStart: "#3b4c64",
      backgroundGradientEnd: "#7795a3",
      profilePictureRadius: "1rem",
      profilePictureBorderColor: "#363c40",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#ebe8e8",
      slugTextWeight: "800",
      slugTextSize: "1.1rem",
      slugFontFamily: "'Roboto', sans-serif",
      headerTextColor: "#ebe8e8",
      headerTextWeight: "400",
      headerTextSize: "1rem",
      headerFontFamily: "'Roboto', sans-serif",
      linkBackgroundColor: "#78909c",
      linkTextColor: "#ebe8e8",
      linkTextWeight: "400",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#363c40",
      linkShadowWeight: "light",
      linkHoverBackgroundColor: "#607d8b",
      linkBorderRadius: "1rem",
      linkPadding: "0.5rem",
      iconBackgroundColor: "#607d8b",
      isIconShadow: true,
      iconShadowColor: "#363c40",
      iconShadowWeight: "medium",
      iconLogoColor: "#ebe8e8",
      iconHoverBackgroundColor: "#78909c",
    },
  },
  {
    title: "Straw",
    preferences: {
      backgroundType: "FLAT",
      backgroundColor: "#f4e1a6",
      profilePictureRadius: "0.5rem",
      profilePictureBorderColor: "#8c6239",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#8c6239",
      slugTextWeight: "700",
      slugTextSize: "1.1rem",
      slugFontFamily: "'Lora', serif",
      headerTextColor: "#8c6239",
      headerTextWeight: "600",
      headerTextSize: "1.1rem",
      headerFontFamily: "'Roboto', sans-serif",
      linkBackgroundColor: "#e6c07b",
      linkTextColor: "#5e4223",
      linkTextWeight: "600",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#c4a267",
      linkShadowWeight: "medium",
      linkHoverBackgroundColor: "#c4a267",
      linkBorderRadius: "1rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#e6c07b",
      isIconShadow: true,
      iconShadowColor: "#8c6239",
      iconShadowWeight: "medium",
      iconLogoColor: "#5e4223",
      iconHoverBackgroundColor: "#c4a267",
    },
  },
  {
    title: "Ultraviolet",
    preferences: {
      backgroundType: "GRADIENT",
      backgroundGradientStart: "#0e0624",
      backgroundGradientEnd: "#000000",
      profilePictureRadius: "5rem",
      profilePictureBorderColor: "#9c27b0",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#b39ddb",
      slugTextWeight: "700",
      slugTextSize: "1.25rem",
      slugFontFamily: "'Audiowide', sans-serif",
      headerTextColor: "#b39ddb",
      headerTextWeight: "600",
      headerTextSize: "1rem",
      headerFontFamily: "'Ubuntu Mono', monospace",
      linkBackgroundColor: "#090612",
      linkTextColor: "#ebe8e8",
      linkTextWeight: "600",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#9c27b0",
      linkShadowWeight: "medium",
      linkHoverBackgroundColor: "#1f1638",
      linkBorderRadius: "1rem",
      linkPadding: "0.85rem",
      iconBackgroundColor: "#333333",
      isIconShadow: true,
      iconShadowColor: "#b3c2a3",
      iconShadowWeight: "light",
      iconLogoColor: "#ebe8e8",
      iconHoverBackgroundColor: "#444444",
    },
  },
  {
    title: "Crayons",
    preferences: {
      backgroundType: "FLAT",
      backgroundColor: "#ececec",
      profilePictureRadius: "5rem",
      profilePictureBorderColor: "#8c6239",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#547b94",
      slugTextWeight: "800",
      slugTextSize: "1.25rem",
      slugFontFamily: "'Ribeye', serif",
      headerTextColor: "#bc7775",
      headerTextWeight: "600",
      headerTextSize: "1.1rem",
      headerFontFamily: "'Ribeye Marrow', serif",
      linkBackgroundColor: "#efb6e5",
      linkTextColor: "#423634",
      linkTextWeight: "700",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Lora', serif",
      isLinkShadow: false,
      linkHoverBackgroundColor: "#bc8fb4",
      linkBorderRadius: "1rem",
      linkPadding: "0.85rem",
      iconBackgroundColor: "#fde08d",
      isIconShadow: true,
      iconShadowColor: "#596e52",
      iconShadowWeight: "light",
      iconLogoColor: "#374234",
      iconHoverBackgroundColor: "#cab270",
    },
  },
  {
    title: "China",
    preferences: {
      backgroundType: "GRADIENT",
      backgroundGradientStart: "#f0e4d7",
      backgroundGradientEnd: "#99ad8c",
      profilePictureRadius: "5rem",
      profilePictureBorderColor: "#8c6239",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#b5631d",
      slugTextWeight: "800",
      slugTextSize: "1.25rem",
      slugFontFamily: "'Amarante', serif",
      headerTextColor: "#bf9339",
      headerTextWeight: "600",
      headerTextSize: "1.1rem",
      headerFontFamily: "'Roboto', sans-serif",
      linkBackgroundColor: "#b5631d",
      linkTextColor: "#ede2cc",
      linkTextWeight: "700",
      linkTextSize: "0.8rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#572e13",
      linkShadowWeight: "heavy",
      linkHoverBackgroundColor: "#bf540d",
      linkBorderRadius: "1rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#b5631d",
      isIconShadow: true,
      iconShadowColor: "#572e13",
      iconShadowWeight: "medium",
      iconLogoColor: "#f4e4c7",
      iconHoverBackgroundColor: "#572e13",
    },
  },
  {
    title: "Bleu de France",
    preferences: {
      backgroundType: "FLAT",
      backgroundColor: "#318ce7",
      profilePictureRadius: "1rem",
      profilePictureBorderColor: "#0d3c6c",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#ffffff",
      slugTextWeight: "800",
      slugTextSize: "1.1rem",
      slugFontFamily: "'Montserrat', sans-serif",
      headerTextColor: "#ffffff",
      headerTextWeight: "600",
      headerTextSize: "1rem",
      headerFontFamily: "'Roboto', sans-serif",
      linkBackgroundColor: "#2673c1",
      linkTextColor: "#ffffff",
      linkTextWeight: "600",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#1a5794",
      linkShadowWeight: "medium",
      linkHoverBackgroundColor: "#1a5794",
      linkBorderRadius: "1rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#1a5794",
      isIconShadow: true,
      iconShadowColor: "#0d3c6c",
      iconShadowWeight: "medium",
      iconLogoColor: "#ffffff",
      iconHoverBackgroundColor: "#2673c1",
    },
  },
  {
    title: "Caribbean",
    preferences: {
      backgroundType: "GRADIENT",
      backgroundGradientStart: "#29ab87",
      backgroundGradientEnd: "#ffd700",
      profilePictureRadius: "5rem",
      profilePictureBorderColor: "#8c6239",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#fafafa",
      slugTextWeight: "700",
      slugTextSize: "1.25rem",
      slugFontFamily: "'Righteous', sans-serif",
      headerTextColor: "#fafafa",
      headerTextWeight: "600",
      headerTextSize: "1.1rem",
      headerFontFamily: "'Montserrat', sans-serif",
      linkBackgroundColor: "#ff8c42",
      linkTextColor: "#ffffff",
      linkTextWeight: "600",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Montserrat', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#ff6300",
      linkShadowWeight: "medium",
      linkHoverBackgroundColor: "#ff6300",
      linkBorderRadius: "5rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#ff8c42",
      isIconShadow: true,
      iconShadowColor: "#e65100",
      iconShadowWeight: "medium",
      iconLogoColor: "#ffffff",
      iconHoverBackgroundColor: "#ff6300",
    },
  },
  {
    title: "Cambridge",
    preferences: {
      backgroundType: "FLAT",
      backgroundColor: "#a3c1ad",
      profilePictureRadius: "1rem",
      profilePictureBorderColor: "#556b5d",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#2e3d2f",
      slugTextWeight: "700",
      slugTextSize: "1.5rem",
      slugFontFamily: "'Amarante', serif",
      headerTextColor: "#2e3d2f",
      headerTextWeight: "600",
      headerTextSize: "1.1rem",
      headerFontFamily: "'Amarante', serif",
      linkBackgroundColor: "#768f79",
      linkTextColor: "#ffffff",
      linkTextWeight: "600",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Lora', serif",
      isLinkShadow: true,
      linkShadowColor: "#556b5d",
      linkShadowWeight: "medium",
      linkHoverBackgroundColor: "#556b5d",
      linkBorderRadius: "1rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#556b5d",
      isIconShadow: true,
      iconShadowColor: "#2e3d2f",
      iconShadowWeight: "medium",
      iconLogoColor: "#ffffff",
      iconHoverBackgroundColor: "#768f79",
    },
  },
  {
    title: "Space Cadet",
    preferences: {
      backgroundType: "FLAT",
      backgroundColor: "#2a2d43",
      profilePictureRadius: "5rem",
      profilePictureBorderColor: "#2a2d43",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#c4c7e2",
      slugTextWeight: "400",
      slugTextSize: "1.25rem",
      slugFontFamily: "'Ubuntu Mono', monospace",
      headerTextColor: "#c4c7e2",
      headerTextWeight: "400",
      headerTextSize: "1.1rem",
      headerFontFamily: "'Ubuntu Mono', monospace",
      linkBackgroundColor: "#3b3e68",
      linkTextColor: "#ffffff",
      linkTextWeight: "400",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Ubuntu Mono', monospace",
      isLinkShadow: true,
      linkShadowColor: "#1a1c2d",
      linkShadowWeight: "medium",
      linkHoverBackgroundColor: "#1a1c2d",
      linkBorderRadius: "5rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#3b3e68",
      isIconShadow: true,
      iconShadowColor: "#1a1c2d",
      iconShadowWeight: "medium",
      iconLogoColor: "#ffffff",
      iconHoverBackgroundColor: "#2a2d43",
    },
  },
] as const
