export const THEMES = [
  {
    title: "Mint",
    preferences: {
      backgroundColor: "#4a5d51",
      backgroundType: "FLAT",
      profilePictureRadius: "5rem",
      profilePictureBorderColor: "#3f5243",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#212b29",
      slugTextWeight: "800",
      slugTextSize: "1.25rem",
      slugFontFamily: "'Playfair Display', serif",
      headerTextColor: "#a3b4b0",
      headerTextWeight: "500",
      headerTextSize: "1.1rem",
      headerFontFamily: "'Roboto', sans-serif",
      linkBackgroundColor: "#5e7464",
      linkTextColor: "#171c1b",
      linkTextWeight: "600",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#3f5243",
      linkShadowWeight: "medium",
      linkHoverBackgroundColor: "#3f5243",
      linkBorderRadius: "5rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#3f5243",
      isIconShadow: true,
      iconShadowColor: "#3f5243",
      iconShadowWeight: "medium",
      iconIconColor: "#ebe8e8",
      iconHoverBackgroundColor: "#5e7464",
    },
  },
  {
    title: "Arctic White",
    preferences: {
      backgroundColor: "#e6ecf0",
      backgroundType: "FLAT",
      profilePictureRadius: "1rem",
      profilePictureBorderColor: "#404345",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#2c3e50",
      slugTextWeight: "800",
      slugTextSize: "1.1rem",
      slugFontFamily: "'Roboto', sans-serif",
      headerTextColor: "#2c3e50",
      headerTextWeight: "500",
      headerTextSize: "1rem",
      headerFontFamily: "'Roboto', sans-serif",
      linkBackgroundColor: "#ecf0f1",
      linkTextColor: "#2c3e50",
      linkTextWeight: "500",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#404345",
      linkShadowWeight: "light",
      linkHoverBackgroundColor: "#bdc3c7",
      linkBorderRadius: "1rem",
      linkPadding: "0.5rem",
      iconBackgroundColor: "#bdc3c7",
      isIconShadow: true,
      iconShadowColor: "#404345",
      iconShadowWeight: "medium",
      iconIconColor: "#2c3e50",
      iconHoverBackgroundColor: "#ecf0f1",
    },
  },
  {
    title: "Arctic Blue",
    preferences: {
      backgroundType: "GRADIENT",
      backgroundGradientStart: "#3b4c64",
      backgroundGradientEnd: "#7795a3",
      profilePictureRadius: "1rem",
      profilePictureBorderColor: "#363c40",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#ebe8e8",
      slugTextWeight: "800",
      slugTextSize: "1.1rem",
      slugFontFamily: "'Roboto', sans-serif",
      headerTextColor: "#ebe8e8",
      headerTextWeight: "500",
      headerTextSize: "1rem",
      headerFontFamily: "'Roboto', sans-serif",
      linkBackgroundColor: "#78909c",
      linkTextColor: "#ebe8e8",
      linkTextWeight: "500",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#363c40",
      linkShadowWeight: "light",
      linkHoverBackgroundColor: "#607d8b",
      linkBorderRadius: "1rem",
      linkPadding: "0.5rem",
      iconBackgroundColor: "#607d8b",
      isIconShadow: true,
      iconShadowColor: "#363c40",
      iconShadowWeight: "medium",
      iconIconColor: "#ebe8e8",
      iconHoverBackgroundColor: "#78909c",
    },
  },
  {
    title: "Straw",
    preferences: {
      backgroundColor: "#F4E1A6",
      backgroundType: "FLAT",
      profilePictureRadius: "0.5rem",
      profilePictureBorderColor: "#8C6239",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#8C6239",
      slugTextWeight: "700",
      slugTextSize: "1.1rem",
      slugFontFamily: "'Lora', serif",
      headerTextColor: "#8C6239",
      headerTextWeight: "600",
      headerTextSize: "1.1rem",
      headerFontFamily: "'Roboto', sans-serif",
      linkBackgroundColor: "#E6C07B",
      linkTextColor: "#5E4223",
      linkTextWeight: "600",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#C4A267",
      linkShadowWeight: "medium",
      linkHoverBackgroundColor: "#C4A267",
      linkBorderRadius: "1rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#E6C07B",
      isIconShadow: true,
      iconShadowColor: "#8C6239",
      iconShadowWeight: "medium",
      iconIconColor: "#5E4223",
      iconHoverBackgroundColor: "#C4A267",
    },
  },
  {
    title: "Ultraviolet",
    preferences: {
      backgroundType: "GRADIENT",
      backgroundGradientStart: "#0e0624",
      backgroundGradientEnd: "#000000",
      profilePictureRadius: "5rem",
      profilePictureBorderColor: "#9c27b0",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#b39ddb",
      slugTextWeight: "700",
      slugTextSize: "1.25rem",
      slugFontFamily: "'Audiowide', sans-serif",
      headerTextColor: "#b39ddb",
      headerTextWeight: "600",
      headerTextSize: "1rem",
      headerFontFamily: "'Ubuntu Mono', sans-serif",
      linkBackgroundColor: "#090612",
      linkTextColor: "#ebe8e8",
      linkTextWeight: "600",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#9c27b0",
      linkShadowWeight: "medium",
      linkHoverBackgroundColor: "#1f1638",
      linkBorderRadius: "1rem",
      linkPadding: "0.85rem",
      iconBackgroundColor: "#333333",
      isIconShadow: true,
      iconShadowColor: "#b3c2a3",
      iconShadowWeight: "light",
      iconIconColor: "#ebe8e8",
      iconHoverBackgroundColor: "#444444",
    },
  },
  {
    title: "Crayons",
    preferences: {
      backgroundColor: "#ececec",
      backgroundType: "FLAT",
      profilePictureRadius: "5rem",
      profilePictureBorderColor: "#8C6239",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#547b94",
      slugTextWeight: "800",
      slugTextSize: "1.25rem",
      slugFontFamily: "'Ribeye', serif",
      headerTextColor: "#bc7775",
      headerTextWeight: "600",
      headerTextSize: "1.1rem",
      headerFontFamily: "'Ribeye Marrow', serif",
      linkBackgroundColor: "#efb6e5",
      linkTextColor: "#423634",
      linkTextWeight: "700",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Lora', sans-serif",
      isLinkShadow: false,
      linkHoverBackgroundColor: "#bc8fb4",
      linkBorderRadius: "1rem",
      linkPadding: "0.85rem",
      iconBackgroundColor: "#fde08d",
      isIconShadow: true,
      iconShadowColor: "#596e52",
      iconShadowWeight: "light",
      iconIconColor: "#374234",
      iconHoverBackgroundColor: "#cab270",
    },
  },
  {
    title: "Jet",
    preferences: {
      backgroundColor: "#333333",
      backgroundType: "FLAT",
      profilePictureRadius: "0.5rem",
      profilePictureBorderColor: "#212121",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#ebe8e8",
      slugTextWeight: "700",
      slugTextSize: "1.25rem",
      slugFontFamily: "'Roboto', sans-serif",
      headerTextColor: "#ebe8e8",
      headerTextWeight: "500",
      headerTextSize: "1.25rem",
      headerFontFamily: "'Roboto', sans-serif",
      linkBackgroundColor: "#444444",
      linkTextColor: "#ebe8e8",
      linkTextWeight: "400",
      linkTextSize: "1rem",
      linkFontFamily: "'Noto Sans', sans-serif",
      isLinkShadow: false,
      linkHoverBackgroundColor: "#555555",
      linkBorderRadius: "0.5rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#555555",
      isIconShadow: false,
      iconIconColor: "#ebe8e8",
      iconHoverBackgroundColor: "#444444",
    },
  },
  {
    title: "Vienna",
    preferences: {
      backgroundColor: "#7d6b3e",
      backgroundType: "GRADIENT",
      backgroundGradientStart: "#7d6b3e",
      backgroundGradientEnd: "#a59e62",
      profilePictureBorderColor: "#1b140e",
      profilePictureBorderWidth: "2px",
      profilePictureRadius: "0.5rem",
      slugTextColor: "#4e3b2a",
      slugTextWeight: "800",
      slugTextSize: "1.25rem",
      slugFontFamily: "'Playfair Display', serif",
      headerTextColor: "#4e3b2a",
      headerTextWeight: "600",
      headerTextSize: "1.1rem",
      headerFontFamily: "'Playfair Display', serif",
      linkBackgroundColor: "#8e7e53",
      linkTextColor: "#4e3b2a",
      linkTextWeight: "600",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#4e3b2a",
      linkShadowWeight: "light",
      linkHoverBackgroundColor: "#bdb97c",
      linkBorderRadius: "5rem",
      linkPadding: "0.9rem",
      iconBackgroundColor: "#bdb97c",
      isIconShadow: false,
      iconIconColor: "#ebe8e8",
      iconHoverBackgroundColor: "#8e7e53",
    },
  },
  {
    title: "Midnight Moss",
    preferences: {
      backgroundColor: "#1c2a23",
      backgroundType: "FLAT",
      profilePictureRadius: "5rem",
      profilePictureBorderColor: "#8C6239",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#a3b69e",
      slugTextWeight: "800",
      slugTextSize: "1.1rem",
      slugFontFamily: "'Montserrat', sans-serif",
      headerTextColor: "#a3b69e",
      headerTextWeight: "600",
      headerTextSize: "1.1rem",
      headerFontFamily: "'Lora', sans-serif",
      linkBackgroundColor: "#223c2e",
      linkTextColor: "#a3b69e",
      linkTextWeight: "400",
      linkTextSize: "0.8rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#182b21",
      linkShadowWeight: "light",
      linkHoverBackgroundColor: "#2c4e38",
      linkBorderRadius: "5rem",
      linkPadding: "0.5rem",
      iconBackgroundColor: "#223c2e",
      isIconShadow: true,
      iconShadowColor: "#182b21",
      iconShadowWeight: "medium",
      iconIconColor: "#a3b69e",
      iconHoverBackgroundColor: "#2c4e38",
    },
  },
  {
    title: "Stormy Slate",
    preferences: {
      backgroundType: "FLAT",
      backgroundColor: "#0b1924",
      profilePictureRadius: "1rem",
      profilePictureBorderColor: "#8C6239",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#a3afb8",
      slugTextWeight: "800",
      slugTextSize: "1.25rem",
      slugFontFamily: "'Roboto', sans-serif",
      headerTextColor: "#a3afb8",
      headerTextWeight: "600",
      headerTextSize: "1.1rem",
      headerFontFamily: "'Roboto', sans-serif",
      linkBackgroundColor: "#0b1924",
      linkTextColor: "#ede2cc",
      linkTextWeight: "700",
      linkTextSize: "0.8rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#a3afb8",
      linkShadowWeight: "light",
      linkHoverBackgroundColor: "#bf540d",
      linkBorderRadius: "1rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#0b1924",
      isIconShadow: true,
      iconShadowColor: "#a3afb8",
      iconShadowWeight: "medium",
      iconIconColor: "#f4e4c7",
      iconHoverBackgroundColor: "#572e13",
    },
  },
  {
    title: "Crimson Noir",
    preferences: {
      backgroundColor: "#3a1d2b",
      backgroundType: "FLAT",
      profilePictureRadius: "1rem",
      profilePictureBorderColor: "#000000",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#f4d5d7",
      slugTextWeight: "500",
      slugTextSize: "1.1rem",
      slugFontFamily: "'Righteous', serif",
      headerTextColor: "#f4d5d7",
      headerTextWeight: "300",
      headerTextSize: "1rem",
      headerFontFamily: "'Roboto', sans-serif",
      linkBackgroundColor: "#5c2a3c",
      linkTextColor: "#f4d5d7",
      linkTextWeight: "500",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Righteous', serif",
      isLinkShadow: true,
      linkShadowColor: "#4a1f2b",
      linkShadowWeight: "light",
      linkHoverBackgroundColor: "#4a1f2b",
      linkBorderRadius: "1rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#5c2a3c",
      isIconShadow: true,
      iconShadowColor: "#4a1f2b",
      iconShadowWeight: "medium",
      iconIconColor: "#f4d5d7",
      iconHoverBackgroundColor: "#4a1f2b",
    },
  },
  {
    title: "Paper",
    preferences: {
      backgroundColor: "#f9f9f9",
      backgroundType: "FLAT",
      profilePictureRadius: "0.5rem",
      profilePictureBorderColor: "#f9f9f9",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#2c3e50",
      slugTextWeight: "600",
      slugTextSize: "1.1rem",
      slugFontFamily: "'Roboto', sans-serif",
      headerTextColor: "#2c3e50",
      headerTextWeight: "500",
      headerTextSize: "1.1rem",
      headerFontFamily: "'Roboto', sans-serif",
      linkBackgroundColor: "#ebe8e8",
      linkTextColor: "#2c3e50",
      linkTextWeight: "400",
      linkTextSize: "1rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#333436",
      linkShadowWeight: "light",
      linkHoverBackgroundColor: "#f0f0f0",
      linkBorderRadius: "0.5rem",
      linkPadding: "0.85rem",
      iconBackgroundColor: "#ebe8e8",
      isIconShadow: true,
      iconShadowColor: "#333436",
      iconShadowWeight: "light",
      iconIconColor: "#2c3e50",
      iconHoverBackgroundColor: "#f0f0f0",
    },
  },
  {
    title: "Oceanic Abyss",
    preferences: {
      backgroundType: "GRADIENT",
      backgroundGradientStart: "#011f27",
      backgroundGradientEnd: "#063852",
      profilePictureRadius: "1rem",
      profilePictureBorderColor: "#000000",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#3da19a",
      slugTextWeight: "600",
      slugTextSize: "1rem",
      slugFontFamily: "'Roboto', sans-serif",
      headerTextColor: "#3da19a",
      headerTextWeight: "500",
      headerTextSize: "1rem",
      headerFontFamily: "'Roboto', sans-serif",
      linkBackgroundColor: "#053940",
      linkTextColor: "#3da19a",
      linkTextWeight: "500",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: false,
      linkHoverBackgroundColor: "#023a44",
      linkBorderRadius: "1rem",
      linkPadding: "0.85rem",
      iconBackgroundColor: "#053940",
      isIconShadow: true,
      iconShadowColor: "#023a44",
      iconShadowWeight: "heavy",
      iconIconColor: "#3da19a",
      iconHoverBackgroundColor: "#023a44",
    },
  },
  {
    title: "China",
    preferences: {
      backgroundType: "GRADIENT",
      backgroundGradientStart: "#f0e4d7",
      backgroundGradientEnd: "#99ad8c",
      profilePictureRadius: "5rem",
      profilePictureBorderColor: "#8C6239",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#b5631d",
      slugTextWeight: "800",
      slugTextSize: "1.25rem",
      slugFontFamily: "'Amarante', serif",
      headerTextColor: "#bf9339",
      headerTextWeight: "600",
      headerTextSize: "1.1rem",
      headerFontFamily: "'Roboto', sans-serif",
      linkBackgroundColor: "#b5631d",
      linkTextColor: "#ede2cc",
      linkTextWeight: "700",
      linkTextSize: "0.8rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#572e13",
      linkShadowWeight: "heavy",
      linkHoverBackgroundColor: "#bf540d",
      linkBorderRadius: "1rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#b5631d",
      isIconShadow: true,
      iconShadowColor: "#572e13",
      iconShadowWeight: "medium",
      iconIconColor: "#f4e4c7",
      iconHoverBackgroundColor: "#572e13",
    },
  },
  {
    title: "Bleu de France",
    preferences: {
      backgroundColor: "#318CE7",
      backgroundType: "FLAT",
      profilePictureRadius: "1rem",
      profilePictureBorderColor: "#0D3C6C",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#FFFFFF",
      slugTextWeight: "800",
      slugTextSize: "1.1rem",
      slugFontFamily: "'Montserrat', sans-serif",
      headerTextColor: "#FFFFFF",
      headerTextWeight: "600",
      headerTextSize: "1rem",
      headerFontFamily: "'Roboto', sans-serif",
      linkBackgroundColor: "#2673C1",
      linkTextColor: "#FFFFFF",
      linkTextWeight: "600",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#1A5794",
      linkShadowWeight: "medium",
      linkHoverBackgroundColor: "#1A5794",
      linkBorderRadius: "1rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#1A5794",
      isIconShadow: true,
      iconShadowColor: "#0D3C6C",
      iconShadowWeight: "medium",
      iconIconColor: "#FFFFFF",
      iconHoverBackgroundColor: "#2673C1",
    },
  },
  {
    title: "Caribbean",
    preferences: {
      backgroundType: "GRADIENT",
      backgroundGradientStart: "#29AB87",
      backgroundGradientEnd: "#FFD700",
      profilePictureRadius: "5rem",
      profilePictureBorderColor: "#8C6239",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#FAFAFA",
      slugTextWeight: "700",
      slugTextSize: "1.25rem",
      slugFontFamily: "'Righteous', serif",
      headerTextColor: "#FAFAFA",
      headerTextWeight: "600",
      headerTextSize: "1.1rem",
      headerFontFamily: "'Montserrat', sans-serif",
      linkBackgroundColor: "#FF8C42",
      linkTextColor: "#FFFFFF",
      linkTextWeight: "600",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Montserrat', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#FF6300",
      linkShadowWeight: "medium",
      linkHoverBackgroundColor: "#FF6300",
      linkBorderRadius: "5rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#FF8C42",
      isIconShadow: true,
      iconShadowColor: "#E65100",
      iconShadowWeight: "medium",
      iconIconColor: "#FFFFFF",
      iconHoverBackgroundColor: "#FF6300",
    },
  },
  {
    title: "Cambridge",
    preferences: {
      backgroundColor: "#A3C1AD",
      backgroundType: "FLAT",
      profilePictureRadius: "1rem",
      profilePictureBorderColor: "#556B5D",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#2E3D2F",
      slugTextWeight: "700",
      slugTextSize: "1.5rem",
      slugFontFamily: "'Amarante', serif",
      headerTextColor: "#2E3D2F",
      headerTextWeight: "600",
      headerTextSize: "1.1rem",
      headerFontFamily: "'Amarante', serif",
      linkBackgroundColor: "#768F79",
      linkTextColor: "#FFFFFF",
      linkTextWeight: "600",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Lora', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#556B5D",
      linkShadowWeight: "medium",
      linkHoverBackgroundColor: "#556B5D",
      linkBorderRadius: "1rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#556B5D",
      isIconShadow: true,
      iconShadowColor: "#2E3D2F",
      iconShadowWeight: "medium",
      iconIconColor: "#FFFFFF",
      iconHoverBackgroundColor: "#768F79",
    },
  },
  {
    title: "Space Cadet",
    preferences: {
      backgroundColor: "#2A2D43",
      backgroundType: "FLAT",
      profilePictureRadius: "5rem",
      profilePictureBorderColor: "#2A2D43",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#C4C7E2",
      slugTextWeight: "500",
      slugTextSize: "1.25rem",
      slugFontFamily: "'Ubuntu Mono', sans-serif",
      headerTextColor: "#C4C7E2",
      headerTextWeight: "500",
      headerTextSize: "1.1rem",
      headerFontFamily: "'Ubuntu Mono', sans-serif",
      linkBackgroundColor: "#3B3E68",
      linkTextColor: "#FFFFFF",
      linkTextWeight: "400",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Ubuntu Mono', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#1A1C2D",
      linkShadowWeight: "medium",
      linkHoverBackgroundColor: "#1A1C2D",
      linkBorderRadius: "5rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#3B3E68",
      isIconShadow: true,
      iconShadowColor: "#1A1C2D",
      iconShadowWeight: "medium",
      iconIconColor: "#FFFFFF",
      iconHoverBackgroundColor: "#2A2D43",
    },
  },
]
