export const THEMES: { title: string, preferences: UserPreferences }[] = [
  {
    title: "Arctic White",
    preferences: {
      backgroundType: "FLAT",
      backgroundColor: "#e6ecf0",
      profilePictureRadius: "1rem",
      profilePictureBorderColor: "#404345",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#2c3e50",
      slugTextWeight: "800",
      slugTextSize: "1.1rem",
      slugFontFamily: "'Roboto', sans-serif",
      headerTextColor: "#2c3e50",
      headerTextWeight: "400",
      headerTextSize: "1rem",
      headerFontFamily: "'Roboto', sans-serif",
      linkBackgroundColor: "#ecf0f1",
      linkTextColor: "#2c3e50",
      linkTextWeight: "400",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#404345",
      linkShadowWeight: "light",
      linkHoverBackgroundColor: "#bdc3c7",
      linkBorderRadius: "1rem",
      linkPadding: "0.5rem",
      iconBackgroundColor: "#bdc3c7",
      isIconShadow: true,
      iconShadowColor: "#404345",
      iconShadowWeight: "medium",
      iconLogoColor: "#2c3e50",
      iconHoverBackgroundColor: "#ecf0f1",
    },
  },
  {
    title: "Arctic Blue",
    preferences: {
      backgroundType: "GRADIENT",
      backgroundGradientStart: "#3b4c64",
      backgroundGradientEnd: "#7795a3",
      profilePictureRadius: "1rem",
      profilePictureBorderColor: "#363c40",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#ebe8e8",
      slugTextWeight: "800",
      slugTextSize: "1.1rem",
      slugFontFamily: "'Roboto', sans-serif",
      headerTextColor: "#ebe8e8",
      headerTextWeight: "400",
      headerTextSize: "1rem",
      headerFontFamily: "'Roboto', sans-serif",
      linkBackgroundColor: "#78909c",
      linkTextColor: "#ebe8e8",
      linkTextWeight: "400",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#363c40",
      linkShadowWeight: "light",
      linkHoverBackgroundColor: "#607d8b",
      linkBorderRadius: "1rem",
      linkPadding: "0.5rem",
      iconBackgroundColor: "#607d8b",
      isIconShadow: true,
      iconShadowColor: "#363c40",
      iconShadowWeight: "medium",
      iconLogoColor: "#ebe8e8",
      iconHoverBackgroundColor: "#78909c",
    },
  },
  {
    title: "Forest Floor",
    preferences: {
      backgroundType: "FLAT",
      backgroundColor: "#1a2e1a",
      profilePictureRadius: "1rem",
      profilePictureBorderColor: "#4a6741",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#c9d6c3",
      slugTextWeight: "700",
      slugTextSize: "1.1rem",
      slugFontFamily: "'Lora', serif",
      headerTextColor: "#a8b8a0",
      headerTextWeight: "400",
      headerTextSize: "1rem",
      headerFontFamily: "'Roboto', sans-serif",
      linkBackgroundColor: "#2d4a2d",
      linkTextColor: "#e8f0e5",
      linkTextWeight: "600",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#1a2e1a",
      linkShadowWeight: "heavy",
      linkHoverBackgroundColor: "#3d5a3d",
      linkBorderRadius: "1rem",
      linkPadding: "0.85rem",
      iconBackgroundColor: "#3d5a3d",
      isIconShadow: true,
      iconShadowColor: "#1a2e1a",
      iconShadowWeight: "medium",
      iconLogoColor: "#e8f0e5",
      iconHoverBackgroundColor: "#4a6741",
    },
  },
  {
    title: "Straw",
    preferences: {
      backgroundType: "FLAT",
      backgroundColor: "#f4e1a6",
      profilePictureRadius: "0.5rem",
      profilePictureBorderColor: "#8c6239",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#8c6239",
      slugTextWeight: "700",
      slugTextSize: "1.1rem",
      slugFontFamily: "'Lora', serif",
      headerTextColor: "#8c6239",
      headerTextWeight: "600",
      headerTextSize: "1.1rem",
      headerFontFamily: "'Roboto', sans-serif",
      linkBackgroundColor: "#e6c07b",
      linkTextColor: "#5e4223",
      linkTextWeight: "600",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#c4a267",
      linkShadowWeight: "medium",
      linkHoverBackgroundColor: "#c4a267",
      linkBorderRadius: "1rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#e6c07b",
      isIconShadow: true,
      iconShadowColor: "#8c6239",
      iconShadowWeight: "medium",
      iconLogoColor: "#5e4223",
      iconHoverBackgroundColor: "#c4a267",
    },
  },
  {
    title: "Crayons",
    preferences: {
      backgroundType: "FLAT",
      backgroundColor: "#ececec",
      profilePictureRadius: "5rem",
      profilePictureBorderColor: "#8c6239",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#547b94",
      slugTextWeight: "800",
      slugTextSize: "1.25rem",
      slugFontFamily: "'Ribeye', serif",
      headerTextColor: "#bc7775",
      headerTextWeight: "600",
      headerTextSize: "1.1rem",
      headerFontFamily: "'Ribeye Marrow', serif",
      linkBackgroundColor: "#efb6e5",
      linkTextColor: "#423634",
      linkTextWeight: "700",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Lora', serif",
      isLinkShadow: false,
      linkHoverBackgroundColor: "#bc8fb4",
      linkBorderRadius: "1rem",
      linkPadding: "0.85rem",
      iconBackgroundColor: "#fde08d",
      isIconShadow: true,
      iconShadowColor: "#596e52",
      iconShadowWeight: "light",
      iconLogoColor: "#374234",
      iconHoverBackgroundColor: "#cab270",
    },
  },
  {
    title: "China",
    preferences: {
      backgroundType: "GRADIENT",
      backgroundGradientStart: "#f0e4d7",
      backgroundGradientEnd: "#99ad8c",
      profilePictureRadius: "5rem",
      profilePictureBorderColor: "#8c6239",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#b5631d",
      slugTextWeight: "800",
      slugTextSize: "1.25rem",
      slugFontFamily: "'Amarante', serif",
      headerTextColor: "#bf9339",
      headerTextWeight: "600",
      headerTextSize: "1.1rem",
      headerFontFamily: "'Roboto', sans-serif",
      linkBackgroundColor: "#b5631d",
      linkTextColor: "#ede2cc",
      linkTextWeight: "700",
      linkTextSize: "0.8rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#572e13",
      linkShadowWeight: "heavy",
      linkHoverBackgroundColor: "#bf540d",
      linkBorderRadius: "1rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#b5631d",
      isIconShadow: true,
      iconShadowColor: "#572e13",
      iconShadowWeight: "medium",
      iconLogoColor: "#f4e4c7",
      iconHoverBackgroundColor: "#572e13",
    },
  },
  {
    title: "Bleu de France",
    preferences: {
      backgroundType: "FLAT",
      backgroundColor: "#318ce7",
      profilePictureRadius: "1rem",
      profilePictureBorderColor: "#0d3c6c",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#ffffff",
      slugTextWeight: "800",
      slugTextSize: "1.1rem",
      slugFontFamily: "'Montserrat', sans-serif",
      headerTextColor: "#ffffff",
      headerTextWeight: "600",
      headerTextSize: "1rem",
      headerFontFamily: "'Roboto', sans-serif",
      linkBackgroundColor: "#2673c1",
      linkTextColor: "#ffffff",
      linkTextWeight: "600",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#1a5794",
      linkShadowWeight: "medium",
      linkHoverBackgroundColor: "#1a5794",
      linkBorderRadius: "1rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#1a5794",
      isIconShadow: true,
      iconShadowColor: "#0d3c6c",
      iconShadowWeight: "medium",
      iconLogoColor: "#ffffff",
      iconHoverBackgroundColor: "#2673c1",
    },
  },
  {
    title: "Fiji",
    preferences: {
      backgroundType: "GRADIENT",
      backgroundGradientStart: "#1ba098",
      backgroundGradientEnd: "#ffd700",
      profilePictureRadius: "5rem",
      profilePictureBorderColor: "#0d7a72",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#ffffff",
      slugTextWeight: "700",
      slugTextSize: "1.25rem",
      slugFontFamily: "'Righteous', sans-serif",
      headerTextColor: "#f0f8f7",
      headerTextWeight: "600",
      headerTextSize: "1.1rem",
      headerFontFamily: "'Montserrat', sans-serif",
      linkBackgroundColor: "#0d7a72",
      linkTextColor: "#ffffff",
      linkTextWeight: "600",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Montserrat', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#095952",
      linkShadowWeight: "medium",
      linkHoverBackgroundColor: "#095952",
      linkBorderRadius: "5rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#0d7a72",
      isIconShadow: true,
      iconShadowColor: "#095952",
      iconShadowWeight: "medium",
      iconLogoColor: "#ffffff",
      iconHoverBackgroundColor: "#1ba098",
    },
  },
  {
    title: "Cambridge",
    preferences: {
      backgroundType: "FLAT",
      backgroundColor: "#a3c1ad",
      profilePictureRadius: "1rem",
      profilePictureBorderColor: "#556b5d",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#2e3d2f",
      slugTextWeight: "700",
      slugTextSize: "1.5rem",
      slugFontFamily: "'Amarante', serif",
      headerTextColor: "#2e3d2f",
      headerTextWeight: "600",
      headerTextSize: "1.1rem",
      headerFontFamily: "'Amarante', serif",
      linkBackgroundColor: "#768f79",
      linkTextColor: "#ffffff",
      linkTextWeight: "600",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Lora', serif",
      isLinkShadow: true,
      linkShadowColor: "#556b5d",
      linkShadowWeight: "medium",
      linkHoverBackgroundColor: "#556b5d",
      linkBorderRadius: "1rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#556b5d",
      isIconShadow: true,
      iconShadowColor: "#2e3d2f",
      iconShadowWeight: "medium",
      iconLogoColor: "#ffffff",
      iconHoverBackgroundColor: "#768f79",
    },
  },
  {
    title: "Space Cadet",
    preferences: {
      backgroundType: "FLAT",
      backgroundColor: "#2a2d43",
      profilePictureRadius: "5rem",
      profilePictureBorderColor: "#2a2d43",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#c4c7e2",
      slugTextWeight: "400",
      slugTextSize: "1.25rem",
      slugFontFamily: "'Ubuntu Mono', monospace",
      headerTextColor: "#c4c7e2",
      headerTextWeight: "400",
      headerTextSize: "1.1rem",
      headerFontFamily: "'Ubuntu Mono', monospace",
      linkBackgroundColor: "#3b3e68",
      linkTextColor: "#ffffff",
      linkTextWeight: "400",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Ubuntu Mono', monospace",
      isLinkShadow: true,
      linkShadowColor: "#1a1c2d",
      linkShadowWeight: "medium",
      linkHoverBackgroundColor: "#1a1c2d",
      linkBorderRadius: "5rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#3b3e68",
      isIconShadow: true,
      iconShadowColor: "#1a1c2d",
      iconShadowWeight: "medium",
      iconLogoColor: "#ffffff",
      iconHoverBackgroundColor: "#2a2d43",
    },
  },
  {
    title: "Rise",
    preferences: {
      backgroundType: "GRADIENT",
      backgroundGradientStart: "#ff6b6b",
      backgroundGradientEnd: "#feca57",
      profilePictureRadius: "5rem",
      profilePictureBorderColor: "#ee5a6f",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#2d3436",
      slugTextWeight: "800",
      slugTextSize: "1.25rem",
      slugFontFamily: "'Righteous', sans-serif",
      headerTextColor: "#2d3436",
      headerTextWeight: "600",
      headerTextSize: "1.1rem",
      headerFontFamily: "'Roboto', sans-serif",
      linkBackgroundColor: "#ff7979",
      linkTextColor: "#2d3436",
      linkTextWeight: "600",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#ee5a6f",
      linkShadowWeight: "medium",
      linkHoverBackgroundColor: "#ee5a6f",
      linkBorderRadius: "1rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#ee5a6f",
      isIconShadow: true,
      iconShadowColor: "#c23b4a",
      iconShadowWeight: "medium",
      iconLogoColor: "#ffffff",
      iconHoverBackgroundColor: "#ff7979",
    },
  },
  {
    title: "Obsidian",
    preferences: {
      backgroundType: "FLAT",
      backgroundColor: "#0a0a0a",
      profilePictureRadius: "1rem",
      profilePictureBorderColor: "#1a1a1a",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#e0e0e0",
      slugTextWeight: "700",
      slugTextSize: "1.1rem",
      slugFontFamily: "'Montserrat', sans-serif",
      headerTextColor: "#9e9e9e",
      headerTextWeight: "400",
      headerTextSize: "1rem",
      headerFontFamily: "'Roboto', sans-serif",
      linkBackgroundColor: "#1a1a1a",
      linkTextColor: "#e0e0e0",
      linkTextWeight: "500",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: false,
      linkHoverBackgroundColor: "#2a2a2a",
      linkBorderRadius: "0.5rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#1a1a1a",
      isIconShadow: false,
      iconLogoColor: "#e0e0e0",
      iconHoverBackgroundColor: "#2a2a2a",
    },
  },
  {
    title: "Sakura",
    preferences: {
      backgroundType: "GRADIENT",
      backgroundGradientStart: "#ffeef8",
      backgroundGradientEnd: "#ffc7e3",
      profilePictureRadius: "5rem",
      profilePictureBorderColor: "#d4869c",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#8b5a6f",
      slugTextWeight: "800",
      slugTextSize: "1.25rem",
      slugFontFamily: "'Playfair Display', serif",
      headerTextColor: "#a0717e",
      headerTextWeight: "600",
      headerTextSize: "1.1rem",
      headerFontFamily: "'Lora', serif",
      linkBackgroundColor: "#ffb3d9",
      linkTextColor: "#5a3d47",
      linkTextWeight: "600",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#e699c2",
      linkShadowWeight: "light",
      linkHoverBackgroundColor: "#ff99cc",
      linkBorderRadius: "5rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#ff99cc",
      isIconShadow: true,
      iconShadowColor: "#d4869c",
      iconShadowWeight: "light",
      iconLogoColor: "#5a3d47",
      iconHoverBackgroundColor: "#ffb3d9",
    },
  },

  {
    title: "Rust",
    preferences: {
      backgroundType: "FLAT",
      backgroundColor: "#3d2817",
      profilePictureRadius: "1rem",
      profilePictureBorderColor: "#6b4423",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#e8d5c4",
      slugTextWeight: "800",
      slugTextSize: "1.1rem",
      slugFontFamily: "'Montserrat', sans-serif",
      headerTextColor: "#c9b8a8",
      headerTextWeight: "400",
      headerTextSize: "1rem",
      headerFontFamily: "'Roboto', sans-serif",
      linkBackgroundColor: "#8b5a3c",
      linkTextColor: "#faf3ed",
      linkTextWeight: "600",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#5c3a21",
      linkShadowWeight: "heavy",
      linkHoverBackgroundColor: "#6b4423",
      linkBorderRadius: "0.5rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#6b4423",
      isIconShadow: true,
      iconShadowColor: "#3d2817",
      iconShadowWeight: "medium",
      iconLogoColor: "#faf3ed",
      iconHoverBackgroundColor: "#8b5a3c",
    },
  },
  {
    title: "Ultra Violet",
    preferences: {
      backgroundType: "FLAT",
      backgroundColor: "#0f0f0f",
      profilePictureRadius: "1rem",
      profilePictureBorderColor: "#ff006e",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#00f5ff",
      slugTextWeight: "800",
      slugTextSize: "1.1rem",
      slugFontFamily: "'Audiowide', sans-serif",
      headerTextColor: "#ff006e",
      headerTextWeight: "600",
      headerTextSize: "1rem",
      headerFontFamily: "'Ubuntu Mono', monospace",
      linkBackgroundColor: "#1a1a1a",
      linkTextColor: "#00f5ff",
      linkTextWeight: "600",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Ubuntu Mono', monospace",
      isLinkShadow: true,
      linkShadowColor: "#00f5ff",
      linkShadowWeight: "medium",
      linkHoverBackgroundColor: "#2a2a2a",
      linkBorderRadius: "0.5rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#1a1a1a",
      isIconShadow: true,
      iconShadowColor: "#ff006e",
      iconShadowWeight: "medium",
      iconLogoColor: "#00f5ff",
      iconHoverBackgroundColor: "#2a2a2a",
    },
  },
  {
    title: "Space Cadet",
    preferences: {
      backgroundType: "GRADIENT",
      backgroundGradientStart: "#1a1f3a",
      backgroundGradientEnd: "#0d1117",
      profilePictureRadius: "5rem",
      profilePictureBorderColor: "#4a5f8c",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#e6eef9",
      slugTextWeight: "700",
      slugTextSize: "1.25rem",
      slugFontFamily: "'Montserrat', sans-serif",
      headerTextColor: "#b8c5d9",
      headerTextWeight: "400",
      headerTextSize: "1.1rem",
      headerFontFamily: "'Roboto', sans-serif",
      linkBackgroundColor: "#2c3e5f",
      linkTextColor: "#e6eef9",
      linkTextWeight: "600",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#1a2438",
      linkShadowWeight: "heavy",
      linkHoverBackgroundColor: "#1a2438",
      linkBorderRadius: "1rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#2c3e5f",
      isIconShadow: true,
      iconShadowColor: "#1a2438",
      iconShadowWeight: "medium",
      iconLogoColor: "#e6eef9",
      iconHoverBackgroundColor: "#4a5f8c",
    },
  },
  {
    title: "Artifact",
    preferences: {
      backgroundType: "FLAT",
      backgroundColor: "#e07a5f",
      profilePictureRadius: "1rem",
      profilePictureBorderColor: "#3d2917",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#3d2917",
      slugTextWeight: "800",
      slugTextSize: "1.1rem",
      slugFontFamily: "'Amarante', serif",
      headerTextColor: "#5c3a21",
      headerTextWeight: "600",
      headerTextSize: "1rem",
      headerFontFamily: "'Lora', serif",
      linkBackgroundColor: "#c85f44",
      linkTextColor: "#fef6f3",
      linkTextWeight: "600",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#a84832",
      linkShadowWeight: "medium",
      linkHoverBackgroundColor: "#a84832",
      linkBorderRadius: "1rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#a84832",
      isIconShadow: true,
      iconShadowColor: "#7a3421",
      iconShadowWeight: "medium",
      iconLogoColor: "#fef6f3",
      iconHoverBackgroundColor: "#c85f44",
    },
  },
  {
    title: "Graphite",
    preferences: {
      backgroundType: "FLAT",
      backgroundColor: "#2e3338",
      profilePictureRadius: "0.5rem",
      profilePictureBorderColor: "#4a5157",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#e8eaed",
      slugTextWeight: "700",
      slugTextSize: "1.1rem",
      slugFontFamily: "'Montserrat', sans-serif",
      headerTextColor: "#b8bfc6",
      headerTextWeight: "400",
      headerTextSize: "1rem",
      headerFontFamily: "'Roboto', sans-serif",
      linkBackgroundColor: "#3d444b",
      linkTextColor: "#e8eaed",
      linkTextWeight: "500",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: true,
      linkShadowColor: "#1f2326",
      linkShadowWeight: "medium",
      linkHoverBackgroundColor: "#4a5157",
      linkBorderRadius: "0.5rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#3d444b",
      isIconShadow: true,
      iconShadowColor: "#1f2326",
      iconShadowWeight: "medium",
      iconLogoColor: "#e8eaed",
      iconHoverBackgroundColor: "#4a5157",
    },
  },
] as const
