export const themePresets = [
	{
		title: "Mint",
		preferences: {
			backgroundColor: "#4a5d51",
			backgroundType: "FLAT",
			profilePictureRadius: "5rem",
			slugTextColor: "#212b29",
			slugTextWeight: "600",
			slugTextSize: "1.25rem",
			headerTextColor: "#a3b4b0",
			headerTextWeight: "500",
			headerTextSize: "1.1rem",
			linkBackgroundColor: "#5e7464",
			linkTextColor: "#171c1b",
			linkTextWeight: "600",
			linkTextSize: "0.9rem",
			isLinkShadow: true,
			linkShadowColor: "#3f5243",
			linkShadowWeight: "medium",
			linkHoverBackgroundColor: "#3f5243",
			linkBorderRadius: "1rem",
			linkPadding: "0.5rem",
			iconBackgroundColor: "#3f5243",
			isIconShadow: true,
			iconShadowColor: "#3f5243",
			iconShadowWeight: "medium",
			iconIconColor: "#ebe8e8",
			iconHoverBackgroundColor: "#5e7464"
		}
	},

	{
		title: "Arctic White",
		preferences: {
			backgroundColor: "#e6ecf0",
			backgroundType: "FLAT",
			profilePictureRadius: "1rem",
			slugTextColor: "#2c3e50",
			slugTextWeight: "800",
			slugTextSize: "1.1rem",
			headerTextColor: "#2c3e50",
			headerTextWeight: "500",
			headerTextSize: "0.9rem",
			linkBackgroundColor: "#ecf0f1",
			linkTextColor: "#2c3e50",
			linkTextWeight: "500",
			linkTextSize: "0.9rem",
			isLinkShadow: true,
			linkShadowColor: "#404345",
			linkShadowWeight: "light",
			linkHoverBackgroundColor: "#bdc3c7",
			linkBorderRadius: "1rem",
			linkPadding: "0.5rem",
			iconBackgroundColor: "#bdc3c7",
			isIconShadow: true,
			iconShadowColor: "#404345",
			iconShadowWeight: "medium",
			iconIconColor: "#2c3e50",
			iconHoverBackgroundColor: "#ecf0f1"
		}
	},

	{
		title: "Arctic Blue",
		preferences: {
			backgroundType: "GRADIENT",
			backgroundGradientStart: "#3b4c64",
			backgroundGradientEnd: "#7795a3",
			profilePictureRadius: "1rem",
			slugTextColor: "#ebe8e8",
			slugTextWeight: "800",
			slugTextSize: "1.1rem",
			headerTextColor: "#ebe8e8",
			headerTextWeight: "500",
			headerTextSize: "0.9rem",
			linkBackgroundColor: "#78909c",
			linkTextColor: "#ebe8e8",
			linkTextWeight: "500",
			linkTextSize: "0.9rem",
			isLinkShadow: true,
			linkShadowColor: "#363c40",
			linkShadowWeight: "light",
			linkHoverBackgroundColor: "#607d8b",
			linkBorderRadius: "1rem",
			linkPadding: "0.5rem",
			iconBackgroundColor: "#607d8b",
			isIconShadow: true,
			iconShadowColor: "#363c40",
			iconShadowWeight: "medium",
			iconIconColor: "#ebe8e8",
			iconHoverBackgroundColor: "#78909c"
		}
	},

	{
		title: "Tokyo",
		preferences: {
			backgroundType: "GRADIENT",
			backgroundGradientStart: "#0e0624",
			backgroundGradientEnd: "#000000",
			profilePictureRadius: "5rem",
			slugTextColor: "#b39ddb",
			slugTextWeight: "600",
			slugTextSize: "1.25rem",
			headerTextColor: "#b39ddb",
			headerTextWeight: "500",
			headerTextSize: "1.1rem",
			linkBackgroundColor: "#090612",
			linkTextColor: "#ebe8e8",
			linkTextWeight: "600",
			linkTextSize: "0.9rem",
			isLinkShadow: true,
			linkShadowColor: "#9c27b0",
			linkShadowWeight: "medium",
			linkHoverBackgroundColor: "#1f1638",
			linkBorderRadius: "1rem",
			linkPadding: "0.85rem",
			iconBackgroundColor: "#333333",
			isIconShadow: true,
			iconShadowColor: "#b3c2a3",
			iconShadowWeight: "light",
			iconIconColor: "#ebe8e8",
			iconHoverBackgroundColor: "#444444"
		}
	},

	{
		title: "Crayons",
		preferences: {
			backgroundColor: "#f2e7fe",
			backgroundType: "FLAT",
			profilePictureRadius: "5rem",
			slugTextColor: "#3d323b",
			slugTextWeight: "800",
			slugTextSize: "1.25rem",
			headerTextColor: "#4a4a4a",
			headerTextWeight: "600",
			headerTextSize: "1.1rem",
			linkBackgroundColor: "#d99696",
			linkTextColor: "#423634",
			linkTextWeight: "700",
			linkTextSize: "0.9rem",
			isLinkShadow: false,
			linkHoverBackgroundColor: "#ff8080",
			linkBorderRadius: "1rem",
			linkPadding: "0.85rem",
			iconBackgroundColor: "#88b07b",
			isIconShadow: true,
			iconShadowColor: "#596e52",
			iconShadowWeight: "light",
			iconIconColor: "#374234",
			iconHoverBackgroundColor: "#ff8080"
		}
	},

	{
		title: "Eclipse",
		preferences: {
			backgroundType: "GRADIENT",
			backgroundGradientStart: "#bf9632",
			backgroundGradientEnd: "#15284a",
			profilePictureRadius: "0.5rem",
			slugTextColor: "#e8e4da",
			slugTextWeight: "800",
			slugTextSize: "1rem",
			headerTextColor: "#e8e4da",
			headerTextWeight: "600",
			headerTextSize: "1.1rem",
			linkBackgroundColor: "#0d1626",
			linkTextColor: "#e8e4da",
			linkTextWeight: "600",
			linkTextSize: "0.8rem",
			isLinkShadow: true,
			linkShadowColor: "#0d0f12",
			linkShadowWeight: "heavy",
			linkHoverBackgroundColor: "#3d392f",
			linkBorderRadius: "5rem",
			linkPadding: "0.9rem",
			iconBackgroundColor: "#3d392f",
			isIconShadow: true,
			iconShadowColor: "#171615",
			iconShadowWeight: "light",
			iconIconColor: "#e8e4da",
			iconHoverBackgroundColor: "#171615"
		}
	},

	{
		title: "Purple Rain",
		preferences: {
			backgroundType: "GRADIENT",
			backgroundGradientStart: "#1a0033",
			backgroundGradientEnd: "#0a0112",
			profilePictureRadius: "1rem",
			slugTextColor: "#b9c5d3",
			slugTextWeight: "700",
			slugTextSize: "1rem",
			headerTextColor: "#b9c5d3",
			headerTextWeight: "500",
			headerTextSize: "0.9rem",
			linkBackgroundColor: "#1a0033",
			linkTextColor: "#8d799c",
			linkTextWeight: "600",
			linkTextSize: "0.8rem",
			isLinkShadow: true,
			linkShadowColor: "#3d004f",
			linkShadowWeight: "medium",
			linkHoverBackgroundColor: "#3d004f",
			linkBorderRadius: "1rem",
			linkPadding: "0.75rem",
			iconBackgroundColor: "#3b2d42",
			isIconShadow: false,
			iconIconColor: "#8d799c",
			iconHoverBackgroundColor: "#1a0033"
		}
	},

	{
		title: "Jet",
		preferences: {
			backgroundColor: "#333333",
			backgroundType: "FLAT",
			profilePictureRadius: "0.5rem",
			slugTextColor: "#ebe8e8",
			slugTextWeight: "700",
			slugTextSize: "1.25rem",
			headerTextColor: "#ebe8e8",
			headerTextWeight: "500",
			headerTextSize: "1.1rem",
			linkBackgroundColor: "#444444",
			linkTextColor: "#ebe8e8",
			linkTextWeight: "600",
			linkTextSize: "1rem",
			isLinkShadow: false,
			linkHoverBackgroundColor: "#555555",
			linkBorderRadius: "0.5rem",
			linkPadding: "0.75rem",
			iconBackgroundColor: "#555555",
			isIconShadow: false,
			iconIconColor: "#ebe8e8",
			iconHoverBackgroundColor: "#444444"
		}
	},

	{
		title: "Vienna",
		preferences: {
			backgroundColor: "#7d6b3e",
			backgroundType: "GRADIENT",
			backgroundGradientStart: "#7d6b3e",
			backgroundGradientEnd: "#a59e62",
			profilePictureRadius: "0.5rem",
			slugTextColor: "#4e3b2a",
			slugTextWeight: "800",
			slugTextSize: "1rem",
			headerTextColor: "#4e3b2a",
			headerTextWeight: "600",
			headerTextSize: "1.1rem",
			linkBackgroundColor: "#8e7e53",
			linkTextColor: "#4e3b2a",
			linkTextWeight: "600",
			linkTextSize: "0.9rem",
			isLinkShadow: true,
			linkShadowColor: "#4e3b2a",
			linkShadowWeight: "light",
			linkHoverBackgroundColor: "#bdb97c",
			linkBorderRadius: "5rem",
			linkPadding: "0.9rem",
			iconBackgroundColor: "#bdb97c",
			isIconShadow: false,
			iconIconColor: "#ebe8e8",
			iconHoverBackgroundColor: "#8e7e53"
		}
	},

	{
		title: "Paper",
		preferences: {
			backgroundColor: "#f9f9f9",
			backgroundType: "FLAT",
			profilePictureRadius: "0.5rem",
			slugTextColor: "#2c3e50",
			slugTextWeight: "600",
			slugTextSize: "1.1rem",
			headerTextColor: "#2c3e50",
			headerTextWeight: "500",
			headerTextSize: "1.1rem",
			linkBackgroundColor: "#ebe8e8",
			linkTextColor: "#2c3e50",
			linkTextWeight: "400",
			linkTextSize: "1rem",
			isLinkShadow: true,
			linkShadowColor: "#333436",
			linkShadowWeight: "light",
			linkHoverBackgroundColor: "#f0f0f0",
			linkBorderRadius: "0.5rem",
			linkPadding: "0.85rem",
			iconBackgroundColor: "#ebe8e8",
			isIconShadow: true,
			iconShadowColor: "#333436",
			iconShadowWeight: "light",
			iconIconColor: "#2c3e50",
			iconHoverBackgroundColor: "#f0f0f0"
		}
	},

	{
		title: "Midnight Moss",
		preferences: {
			backgroundColor: "#1c2a23",
			backgroundType: "FLAT",
			profilePictureRadius: "5rem",
			slugTextColor: "#a3b69e",
			slugTextWeight: "800",
			slugTextSize: "1.1rem",
			headerTextColor: "#a3b69e",
			headerTextWeight: "600",
			headerTextSize: "0.9rem",
			linkBackgroundColor: "#223c2e",
			linkTextColor: "#a3b69e",
			linkTextWeight: "400",
			linkTextSize: "0.8rem",
			isLinkShadow: true,
			linkShadowColor: "#182b21",
			linkShadowWeight: "light",
			linkHoverBackgroundColor: "#2c4e38",
			linkBorderRadius: "5rem",
			linkPadding: "0.5rem",
			iconBackgroundColor: "#223c2e",
			isIconShadow: true,
			iconShadowColor: "#182b21",
			iconShadowWeight: "medium",
			iconIconColor: "#a3b69e",
			iconHoverBackgroundColor: "#2c4e38"
		}
	},

	{
		title: "Stormy Slate",
		preferences: {
			backgroundColor: "#4f5b63",
			backgroundType: "FLAT",
			profilePictureRadius: "1rem",
			slugTextColor: "#c4cfd3",
			slugTextWeight: "600",
			slugTextSize: "1.1rem",
			headerTextColor: "#c4cfd3",
			headerTextWeight: "400",
			headerTextSize: "1.1rem",
			linkBackgroundColor: "#627d88",
			linkTextColor: "#c4cfd3",
			linkTextWeight: "600",
			linkTextSize: "0.9rem",
			isLinkShadow: true,
			linkShadowColor: "#4f5b63",
			linkShadowWeight: "light",
			linkHoverBackgroundColor: "#484f52",
			linkBorderRadius: "1rem",
			linkPadding: "0.5rem",
			iconBackgroundColor: "#484f52",
			isIconShadow: true,
			iconShadowColor: "#5c6d74",
			iconShadowWeight: "medium",
			iconIconColor: "#c4cfd3",
			iconHoverBackgroundColor: "#5c6d74"
		}
	},

	{
		title: "Crimson Noir",
		preferences: {
			backgroundColor: "#3a1d2b",
			backgroundType: "FLAT",
			profilePictureRadius: "1rem",
			slugTextColor: "#f4d5d7",
			slugTextWeight: "500",
			slugTextSize: "1rem",
			headerTextColor: "#f4d5d7",
			headerTextWeight: "300",
			headerTextSize: "1.1rem",
			linkBackgroundColor: "#5c2a3c",
			linkTextColor: "#f4d5d7",
			linkTextWeight: "500",
			linkTextSize: "0.9rem",
			isLinkShadow: true,
			linkShadowColor: "#4a1f2b",
			linkShadowWeight: "light",
			linkHoverBackgroundColor: "#4a1f2b",
			linkBorderRadius: "1rem",
			linkPadding: "0.75rem",
			iconBackgroundColor: "#5c2a3c",
			isIconShadow: true,
			iconShadowColor: "#4a1f2b",
			iconShadowWeight: "medium",
			iconIconColor: "#f4d5d7",
			iconHoverBackgroundColor: "#4a1f2b"
		}
	},

	{
		title: "Oceanic Abyss",
		preferences: {
			backgroundType: "GRADIENT",
			backgroundGradientStart: "#011f27",
			backgroundGradientEnd: "#063852",
			profilePictureRadius: "1rem",
			slugTextColor: "#3da19a",
			slugTextWeight: "600",
			slugTextSize: "1rem",
			headerTextColor: "#3da19a",
			headerTextWeight: "500",
			headerTextSize: "0.9rem",
			linkBackgroundColor: "#053940",
			linkTextColor: "#3da19a",
			linkTextWeight: "500",
			linkTextSize: "0.9rem",
			isLinkShadow: false,
			linkHoverBackgroundColor: "#023a44",
			linkBorderRadius: "1rem",
			linkPadding: "0.85rem",
			iconBackgroundColor: "#053940",
			isIconShadow: true,
			iconShadowColor: "#023a44",
			iconShadowWeight: "heavy",
			iconIconColor: "#3da19a",
			iconHoverBackgroundColor: "#023a44"
		}
	},

	{
		title: "China",
		preferences: {
			backgroundType: "GRADIENT",
			backgroundGradientStart: "#f0e4d7",
			backgroundGradientEnd: "#99ad8c",
			profilePictureRadius: "1rem",
			slugTextColor: "#b5631d",
			slugTextWeight: "800",
			slugTextSize: "1.25rem",
			headerTextColor: "#bf9339",
			headerTextWeight: "600",
			headerTextSize: "1.1rem",
			linkBackgroundColor: "#b5631d",
			linkTextColor: "#ede2cc",
			linkTextWeight: "700",
			linkTextSize: "0.8rem",
			isLinkShadow: true,
			linkShadowColor: "#572e13",
			linkShadowWeight: "heavy",
			linkHoverBackgroundColor: "#bf540d",
			linkBorderRadius: "1rem",
			linkPadding: "0.75rem",
			iconBackgroundColor: "#b5631d",
			isIconShadow: true,
			iconShadowColor: "#572e13",
			iconShadowWeight: "medium",
			iconIconColor: "#f4e4c7",
			iconHoverBackgroundColor: "#572e13"
		}
	}
]
